Import('dev source_path')

ret = None

if dev.is_win32():
	env, target, sources = dev.prepare_build(source_path, 'aintl', '*.c')

	env.Append(CPPDEFINES=['LOCALEDIR=\\"\\"', 'LOCALE_ALIAS_PATH=\\"\\"', 'INSTALLDIR=\\"\\"', 'LIBDIR=\\"\\"', 'BUILDING_LIBINTL', 
		'BUILDING_DLL', 'IN_LIBINTL', 'ENABLE_RELOCATABLE=1', 'NO_XMALLOC', 'HAVE_CONFIG_H',
		'set_relocation_prefix=libintl_set_relocation_prefix', 'relocate=libintl_relocate'])
	env.Append(CPPPATH='#/intl')

	dev.env.Append(LIBS=['aintl'])
	import os
	dev.env.Append(LIBPATH=[os.path.dirname(target)])
	ret = env.SharedLibrary(target, sources)
else:
	print "intl only built on win32"

Return('ret')
