Import('dev source_path setLuaEnv')

env, target, sources = dev.prepare_build(source_path, 'lfs', source_glob = '*.c')
env['SHLIBPREFIX'] = ''
env['CYGDLLPREFIX'] = ''

setLuaEnv(env)

ret = env.SharedLibrary(target, sources)

Return('ret')
