Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'lfs', source_glob = '*.c')
env['SHLIBPREFIX'] = ''

env.Append(CPPPATH = ['#/lua/'])
env.Append(LIBS = ['alua'])

ret = env.SharedLibrary(target, sources)

Return('ret')
