Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'Script', shared_precompiled_header = 'stdinc')
env['SHLIBPREFIX'] = ''

env.Append(CPPPATH = ['#/lua/', '.', '#'])
env.Append(LIBS = ['adchpp', 'alua'])

ret = env.SharedLibrary(target, sources)

Return('ret')
