# vim: set filetype=py

Import('dev source_path')
env, target, sources = dev.prepare_build(source_path, 'adchpp')

env.Append(CPPPATH = ['.', '#'])
env.Append(LIBS=['adchpp'])
   
ret = env.Program(target, sources)

Return('ret')