Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'Bloom', shared_precompiled_header = 'stdinc')
env['SHLIBPREFIX'] = ''

env.Append(CPPPATH = ['#'])
env.Append(LIBS = ['adchpp'])

ret = env.SharedLibrary(target, sources)

Return('ret')
