Import('dev source_path')

env, target, sources = dev.prepare_build(source_path, 'Bloom')
env['SHLIBPREFIX'] = ''

if 'gcc' in env['TOOLS']:
	env['GchSh'] = env.GchSh('stdinc.h')[0]

env.Append(CPPPATH = ['#'])
env.Append(LIBS = ['adchpp'])

ret = env.SharedLibrary(target, sources)

Return('ret')
